apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: download
spec:
  template:
    spec:
      containers:
        - image: "us-west2-docker.pkg.dev/pulsar-357404/package-frontend/download:2.0.1"
